///Home页面
final List<String> cardImagePaths = [
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
];
final List<String> cardTitles =[
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',
];
final List<String> cardTexts = [
  '瑞星',
  '晨曦',
  '彩虹风',
  '幻影笛',
  '蓝月影',
  '燕荷',
  '心语流年',
  '星辰璀璨',
];
final List<String> titles = [
  '星空的梦想',
  '白熊',
  '星空的梦想',
  '白熊',
  '星空的梦想',
  '白熊',
  '星空的梦想',
  '白熊',
];
final List<String> texts = [
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
];

final List<String> imagePaths = [
  'assets/images/cover_1.jpg',
  'assets/images/cover_2.jpg',
  'assets/images/cover_1.jpg',
  'assets/images/cover_2.jpg',
  'assets/images/cover_1.jpg',
  'assets/images/cover_2.jpg',
  'assets/images/cover_1.jpg',
  'assets/images/cover_2.jpg',
];


///分类页面

final List comprehensive = ['最多追更', '最近更新', '最高评分'];
final List style = [
  '仙侠',
  '都市',
  '军事',
  '游戏',
  '科幻',
  '玄幻',
  '奇幻',
  '武侠',
  '悬疑',
  '轻小说',
];
final List state = ['完结', '连载'];
final List wordNum = [
  '不限',
  '30万以下',
  '30-50万',
  '50-100万',
  '100-200万',
  '200万以上'
];

final List<String> bookImagePaths = [
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
];

final List<String> bookTitles = [
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',
];

///
final List bookTitles_2 = [
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',
];
final List bookImagePaths_2 = [
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
];
final List bookLabels = [
  '瑞星',
  '晨曦',
  '彩虹风',
  '幻影笛',
  '蓝月影',
  '燕荷',
  '心语流年',
  '星辰璀璨',
  '瑞星',
  '晨曦',
  '彩虹风',
  '幻影笛',
  '蓝月影',
  '燕荷',
  '心语流年',
  '星辰璀璨',
];

final List dates = [
  '2020-5-21',
  '2020-3-02',
  '2020-4-24',
  '2021-2-11',
  '2021-7-05',
  '2022-3-07',
  '2022-9-12',
  '2022-10-01',
  '2020-5-21',
  '2020-3-02',
  '2020-4-24',
  '2021-2-11',
  '2021-7-05',
  '2022-3-07',
  '2022-9-12',
  '2022-10-01',
];

final List discoverAuthors =['瑞星',
  '晨曦',
  '彩虹风',
  '幻影笛',
  '蓝月影',
  '燕荷',
  '心语流年',
  '星辰璀璨',
  '瑞星',
  '晨曦',
  '彩虹风',
  '幻影笛',
  '蓝月影',
  '燕荷',
  '心语流年',
  '星辰璀璨',];
final List discoverTitles = [
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',
  '黑猫',
  '青柠汽水',
  '幻の夢',
  '月光下',
  '无职转生',
  '画',
  '少女',
  '玛奇玛',];
final List discoverTexts = [
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
  '在一个充满神秘的星空世界中，少年被一颗神奇的星星引导，踏上了一个前所未有的冒险之旅。',
  '她与白熊建立了一种特殊的纽带，超越了语言和物种的界限。他们一起经历了许多冒险和困难，共同探索北极圈的奇妙之处。',
  '小黑猫只是一只小黑猫，它没有喝过幸福的牛奶；小男孩只是一个小男孩，没有过去也没有未来；在一个樱花盛开晚风徐徐的夜晚，小黑猫遇上了小男孩，小男孩给了它一碗温温的牛奶。',
];
final List discoverScores = [
  '10.0',
  '9.2',
  '8.9',
  '8.5',
  '9.1',
  '7.9',
  '8.4',
  '7.6',
  '9.3',
  '9.2',
  '8.9',
  '8.5',
  '9.1',
  '7.9',
  '8.8',
  '7.7',
];
final List discoverImages = [
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
  'assets/images/illustration_1.jpg',
  'assets/images/illustration_2.jpg',
  'assets/images/illustration_3.jpg',
  'assets/images/illustration_4.jpg',
  'assets/images/illustration_5.jpg',
  'assets/images/illustration_6.jpg',
  'assets/images/illustration_7.jpg',
  'assets/images/illustration_8.jpg',
];